import React from 'react';
import {
  ArrowRightLeft,
  Award,
  Badge,
  Braces,
  Box,
  Combine,
  Contact,
  FileCog,
  FileDown,
  FileText,
  Film,
  GitFork,
  Gift,
  Heart,
  Image,
  KeyRound,
  LayoutTemplate,
  Lock,
  Milestone,
  Music,
  Package,
  Pencil,
  QrCode,
  Quote,
  RotateCcw,
  Scissors,
  Sparkles,
  Smile,
  Table,
  Type,
  User,
  UserCircle,
  Wallet,
  Workflow,
  FileArchive,
  FileJson,
  FileCode,
  FileTerminal,
  FileImage,
  FileAudio,
  FileVideo,
  FileSpreadsheet,
  FileSignature,
  FileLock,
  FileX,
  FilePlus,
  FileSymlink,
  FileKey,
  FileCheck,
  FileUp,
  FileDown as FileDownIcon,
  FileEdit,
  FileSearch,
  FileBox,
  FileArchive as ZipIcon,
  Layers,
  FlipVertical,
  ArrowUpDown,
  Info,
  Trash2,
  Shield,
  Stamp,
  ClipboardList,
  ClipboardEdit,
  Database,
  Code,
  Sheet,
  GanttChartSquare,
  Presentation,
  Book,
  Columns,
  Spline,
  AppWindow,
  Terminal,
} from 'lucide-react';
import { Tool, ToolInfo, ToolCategory } from './types';

const iconSize = { width: 28, height: 28, strokeWidth: 1.5 };

export const TOOLS: ToolInfo[] = [
  // Organize & Modify
  { key: Tool.Merge, title: 'Merge PDF', description: 'Combine multiple PDFs into one.', icon: <Combine {...iconSize} />, category: ToolCategory.Organize },
  { key: Tool.Split, title: 'Split PDF', description: 'Extract pages from a PDF.', icon: <Scissors {...iconSize} />, category: ToolCategory.Organize },
  { key: Tool.DeletePages, title: 'Delete Pages', description: 'Remove specific pages from a PDF.', icon: <Trash2 {...iconSize} />, category: ToolCategory.Organize },
  { key: Tool.RotatePages, title: 'Rotate Pages', description: 'Rotate pages in a PDF document.', icon: <RotateCcw {...iconSize} />, category: ToolCategory.Organize },
  { key: Tool.ReorderPages, title: 'Reorder Pages', description: 'Change the order of pages in a PDF.', icon: <Layers {...iconSize} />, category: ToolCategory.Organize },
  
  // Convert & Extract
  { key: Tool.PdfToWord, title: 'PDF to Word', description: 'Convert your PDF to an editable Word document.', icon: <FileSignature {...iconSize} />, category: ToolCategory.Convert },
  { key: Tool.DocToPdf, title: 'Word to PDF', description: 'Convert Word documents (.doc, .docx) to PDF.', icon: <FileUp {...iconSize} />, category: ToolCategory.Convert },
  { key: Tool.DocToTxt, title: 'Word to Text', description: 'Pull all text content from a Word document.', icon: <Type {...iconSize} />, category: ToolCategory.Convert },
  { key: Tool.MarkdownConvert, title: 'Markdown Converter', description: 'Convert Markdown files to HTML or PDF.', icon: <Book {...iconSize} />, category: ToolCategory.Convert },
  { key: Tool.PptConvert, title: 'PowerPoint Converter', description: 'Convert PowerPoint files to PDF or images.', icon: <Presentation {...iconSize} />, category: ToolCategory.Convert },
  { key: Tool.SpreadsheetConvert, title: 'Spreadsheet Converter', description: 'Convert Excel files to PDF or HTML.', icon: <Sheet {...iconSize} />, category: ToolCategory.Convert },
  { key: Tool.CsvXlsxConvert, title: 'CSV <> Excel Converter', description: 'Convert between CSV and XLSX (Excel) formats.', icon: <Columns {...iconSize} />, category: ToolCategory.Convert },
  { key: Tool.AudioConvert, title: 'Audio Converter', description: 'Convert audio files (WAV, MP3, AAC, etc.).', icon: <FileAudio {...iconSize} />, category: ToolCategory.Convert },
  { key: Tool.VideoConvert, title: 'Video Converter', description: 'Convert video files (MP4, WEBM, GIF, etc.).', icon: <FileVideo {...iconSize} />, category: ToolCategory.Convert },
  { key: Tool.PdfToImages, title: 'PDF to Images', description: 'Convert PDF pages to images (PNG/JPG).', icon: <FileImage {...iconSize} />, category: ToolCategory.Convert },
  { key: Tool.FileExporter, title: 'Text to File', description: 'Save raw text to a file with any extension.', icon: <FileDownIcon {...iconSize} />, category: ToolCategory.Convert },
  { key: Tool.ExtractText, title: 'Extract Text', description: 'Pull all text content from a PDF.', icon: <FileSearch {...iconSize} />, category: ToolCategory.Convert },
  { key: Tool.CadConvert, title: 'CAD to PDF', description: 'Convert DXF files to PDF.', icon: <Spline {...iconSize} />, category: ToolCategory.Convert },

  // Optimize & Secure
  { key: Tool.Compress, title: 'Compress PDF', description: 'Reduce the file size of your PDF.', icon: <FileArchive {...iconSize} />, category: ToolCategory.Optimize },
  { key: Tool.Protect, title: 'Protect PDF', description: 'Add a password to your PDF.', icon: <FileLock {...iconSize} />, category: ToolCategory.Optimize },

  // Annotate & Metadata
  { key: Tool.Watermark, title: 'Add Watermark', description: 'Stamp text onto your PDF pages.', icon: <Stamp {...iconSize} />, category: ToolCategory.Annotate },
  { key: Tool.GetMetadata, title: 'Get Metadata', description: 'View the metadata of a PDF file.', icon: <Info {...iconSize} />, category: ToolCategory.Annotate },
  { key: Tool.SetMetadata, title: 'Set Metadata', description: 'Update the metadata of a PDF file.', icon: <ClipboardEdit {...iconSize} />, category: ToolCategory.Annotate },

  // Developer Tools
  { key: Tool.JsonFormat, title: 'JSON Formatter', description: 'Format or minify your JSON data.', icon: <Braces {...iconSize} />, category: ToolCategory.Developer },
  { key: Tool.DataClean, title: 'Data Cleaner', description: 'Clean and transform your text data.', icon: <Sparkles {...iconSize} />, category: ToolCategory.Developer },
  { key: Tool.ConfigConvert, title: 'Config Converter', description: 'Convert between different config file formats.', icon: <FileCog {...iconSize} />, category: ToolCategory.Developer },
  { key: Tool.CsvJsonConverter, title: 'CSV <> JSON Converter', description: 'Convert between CSV and JSON formats.', icon: <ArrowRightLeft {...iconSize} />, category: ToolCategory.Developer },
  { key: Tool.PasswordGenerator, title: 'Password Generator', description: 'Create strong, random passwords and check their strength.', icon: <KeyRound {...iconSize} />, category: ToolCategory.Developer },

  // Creative Tools
  { key: Tool.QrCodeGenerator, title: 'QR Code Generator', description: 'Generate a QR code from a URL or text.', icon: <QrCode {...iconSize} />, category: ToolCategory.Creative },
  { key: Tool.BasicInvoicePdf, title: 'Basic Invoice PDF', description: 'Create a basic invoice and download it as a PDF.', icon: <FileText {...iconSize} />, category: ToolCategory.Creative },
  { key: Tool.InvitationCard, title: 'Invitation Card', description: 'Design a custom invitation card.', icon: <Gift {...iconSize} />, category: ToolCategory.Creative },
  { key: Tool.CertificateMaker, title: 'Certificate Maker', description: 'Create a custom certificate.', icon: <Award {...iconSize} />, category: ToolCategory.Creative },
  { key: Tool.ResumeBuilder, title: 'Resume Builder', description: 'Create a professional resume from a form.', icon: <User {...iconSize} />, category: ToolCategory.Creative },
  { key: Tool.BusinessCard, title: 'Business Card Maker', description: 'Design a two-sided business card.', icon: <Contact {...iconSize} />, category: ToolCategory.Creative },
  { key: Tool.PosterFlyerDesign, title: 'Poster/Flyer Design', description: 'Design a poster or flyer with text and images.', icon: <LayoutTemplate {...iconSize} />, category: ToolCategory.Creative },
  { key: Tool.QuoteImageCreator, title: 'Quote Image Creator', description: 'Create an image with a quote.', icon: <Quote {...iconSize} />, category: ToolCategory.Creative },
  { key: Tool.TimelineRoadmapBuilder, title: 'Timeline/Roadmap Builder', description: 'Create a timeline with draggable milestones.', icon: <Milestone {...iconSize} />, category: ToolCategory.Creative },
  { key: Tool.MindMapGenerator, title: 'Mind Map Generator', description: 'Create a mind map with a force-directed graph.', icon: <GitFork {...iconSize} />, category: ToolCategory.Creative },
  { key: Tool.AvatarGenerator, title: 'Avatar Generator', description: 'Generate a random avatar.', icon: <UserCircle {...iconSize} />, category: ToolCategory.Creative },
  { key: Tool.FaviconGenerator, title: 'Favicon Generator', description: 'Generate a favicon from text.', icon: <Heart {...iconSize} />, category: ToolCategory.Creative },
  { key: Tool.MemeMaker, title: 'Meme Maker', description: 'Create a meme with top and bottom text.', icon: <Smile {...iconSize} />, category: ToolCategory.Creative },
  { key: Tool.BadgeIdCardMaker, title: 'Badge/ID Card Maker', description: 'Create a badge or ID card.', icon: <Badge {...iconSize} />, category: ToolCategory.Creative },
];